# Generated by Django 5.2.16 on 2026-07-11 06:19

import websites.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('public_key', models.CharField(default=websites.models.generate_public_key, editable=False, max_length=64, unique=True)),
                ('allowed_domains', models.JSONField(default=list, help_text='Exact hostnames or *.example.com wildcards. Do not include schemes or paths.')),
                ('timezone', models.CharField(default='Europe/Istanbul', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
