# Generated by Django 5.2.16 on 2026-07-11 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('pageview', 'Pageview'), ('custom', 'Custom event')], max_length=16)),
                ('event_name', models.CharField(blank=True, max_length=64)),
                ('occurred_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('visitor_hash', models.CharField(max_length=64)),
                ('session_id', models.CharField(max_length=64)),
                ('path', models.CharField(max_length=2048)),
                ('referrer_domain', models.CharField(blank=True, max_length=255)),
                ('referrer_path', models.CharField(blank=True, max_length=2048)),
                ('utm_source', models.CharField(blank=True, max_length=255)),
                ('utm_medium', models.CharField(blank=True, max_length=255)),
                ('utm_campaign', models.CharField(blank=True, max_length=255)),
                ('utm_term', models.CharField(blank=True, max_length=255)),
                ('utm_content', models.CharField(blank=True, max_length=255)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('country_name', models.CharField(blank=True, max_length=100)),
                ('device', models.CharField(blank=True, max_length=32)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(blank=True, max_length=35)),
                ('client_timezone', models.CharField(blank=True, max_length=64)),
                ('viewport_width', models.PositiveIntegerField(default=0)),
                ('viewport_height', models.PositiveIntegerField(default=0)),
                ('screen_width', models.PositiveIntegerField(default=0)),
                ('screen_height', models.PositiveIntegerField(default=0)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='websites.trackedsite')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['site', 'occurred_at'], name='event_site_time_idx'), models.Index(fields=['site', 'visitor_hash', 'occurred_at'], name='event_site_visitor_idx'), models.Index(fields=['site', 'session_id', 'occurred_at'], name='event_site_session_idx'), models.Index(fields=['site', 'event_type', 'occurred_at'], name='event_site_type_idx')],
            },
        ),
    ]
