# Generated by Django 5.2.16 on 2026-07-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticsevent",
            name="city_name",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analyticsevent",
            name="region_code",
            field=models.CharField(blank=True, default="", max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analyticsevent",
            name="region_name",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
    ]
