# Generated by Django 5.2.16 on 2026-08-13 07:27

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0006_agent_contract_records"),
        ("websites", "0005_trackedsite_server_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivePartition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("generation", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("site_id_snapshot", models.PositiveBigIntegerField(db_index=True)),
                (
                    "stream",
                    models.CharField(
                        choices=[("analytics", "Analytics events"), ("bots", "Bot events")],
                        max_length=16,
                    ),
                ),
                ("range_start", models.DateTimeField()),
                ("range_end", models.DateTimeField()),
                ("timezone", models.CharField(max_length=64)),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                ("object_key", models.CharField(blank=True, max_length=1024)),
                ("object_version", models.CharField(blank=True, max_length=255)),
                (
                    "storage_class",
                    models.CharField(
                        choices=[("STANDARD", "S3 queryable"), ("GLACIER", "S3 Glacier")],
                        default="STANDARD",
                        max_length=24,
                    ),
                ),
                ("row_count", models.PositiveBigIntegerField(default=0)),
                ("min_event_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("max_event_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("min_occurred_at", models.DateTimeField(blank=True, null=True)),
                ("max_occurred_at", models.DateTimeField(blank=True, null=True)),
                ("verification_sha256", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("exported", "Exported"),
                            ("verified", "Verified"),
                            ("deleting", "Deleting source"),
                            ("source_deleted", "Source deleted"),
                            ("superseded", "Superseded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("error_message", models.CharField(blank=True, max_length=500)),
                ("exported_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("source_deleted_at", models.DateTimeField(blank=True, null=True)),
                ("transitioned_at", models.DateTimeField(blank=True, null=True)),
                ("restore_requested_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archive_partitions",
                        to="websites.trackedsite",
                    ),
                ),
            ],
            options={
                "ordering": ["range_start", "site_id_snapshot", "stream"],
                "indexes": [
                    models.Index(fields=["status", "range_end"], name="archive_status_end_idx"),
                    models.Index(
                        fields=["site_id_snapshot", "stream", "range_start"],
                        name="archive_site_stream_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("site_id_snapshot", "stream", "range_start", "range_end"),
                        name="archive_site_stream_range_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("range_end__gt", models.F("range_start"))),
                        name="archive_range_ordered",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ColdDataTombstone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("site_id_snapshot", models.PositiveBigIntegerField(db_index=True)),
                (
                    "kind",
                    models.CharField(choices=[("actor", "Actor"), ("site", "Site")], max_length=16),
                ),
                ("actor_hash", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("error_message", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cold_data_tombstones",
                        to="websites.trackedsite",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["site_id_snapshot", "status", "created_at"],
                        name="cold_tombstone_pending_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ColdDeletionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("request_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("site_id_snapshot", models.PositiveBigIntegerField(db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("actor", "Actor"), ("site", "Site")],
                        default="actor",
                        max_length=16,
                    ),
                ),
                ("actor_hash", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("running", "Running"),
                            ("waiting_restore", "Waiting for Glacier restore"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("unknown", "Unknown"),
                        ],
                        default="accepted",
                        max_length=16,
                    ),
                ),
                ("deleted_hot_events", models.PositiveBigIntegerField(default=0)),
                ("rewritten_partitions", models.PositiveIntegerField(default=0)),
                ("deleted_cold_events", models.PositiveBigIntegerField(default=0)),
                ("error_message", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cold_deletion_jobs",
                        to="websites.trackedsite",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["status", "created_at"], name="cold_deletion_status_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyAnalyticsRollup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("day", models.DateField()),
                ("timezone", models.CharField(max_length=64)),
                ("bucket_start", models.DateTimeField()),
                ("bucket_end", models.DateTimeField()),
                ("event_count", models.PositiveBigIntegerField(default=0)),
                ("browser_event_count", models.PositiveBigIntegerField(default=0)),
                ("pageview_count", models.PositiveBigIntegerField(default=0)),
                ("identified_event_count", models.PositiveBigIntegerField(default=0)),
                ("automated_event_count", models.PositiveBigIntegerField(default=0)),
                (
                    "metric_value_sum",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True),
                ),
                ("metric_value_count", models.PositiveBigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_analytics_rollups",
                        to="websites.trackedsite",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["site", "day"], name="daily_analytics_day_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("site", "day"), name="daily_analytics_site_day_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyBotRollup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("day", models.DateField()),
                ("timezone", models.CharField(max_length=64)),
                ("bucket_start", models.DateTimeField()),
                ("bucket_end", models.DateTimeField()),
                ("dimension", models.CharField(max_length=24)),
                ("label", models.CharField(max_length=2048)),
                ("secondary_label", models.CharField(blank=True, max_length=255)),
                ("event_count", models.PositiveBigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_bot_rollups",
                        to="websites.trackedsite",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["site", "dimension", "day"], name="daily_bot_query_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("site", "day", "dimension", "label", "secondary_label"),
                        name="daily_bot_dimension_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyDimensionRollup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("day", models.DateField()),
                ("timezone", models.CharField(max_length=64)),
                ("bucket_start", models.DateTimeField()),
                ("bucket_end", models.DateTimeField()),
                ("dimension", models.CharField(max_length=32)),
                ("label", models.CharField(max_length=2048)),
                ("event_count", models.PositiveBigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_dimension_rollups",
                        to="websites.trackedsite",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["site", "dimension", "day"], name="daily_dimension_query_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("site", "day", "dimension", "label"),
                        name="daily_dimension_row_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyProductEventRollup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("day", models.DateField()),
                ("timezone", models.CharField(max_length=64)),
                ("bucket_start", models.DateTimeField()),
                ("bucket_end", models.DateTimeField()),
                ("event_name", models.CharField(max_length=64)),
                ("event_count", models.PositiveBigIntegerField(default=0)),
                ("identified_event_count", models.PositiveBigIntegerField(default=0)),
                (
                    "value_sum",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True),
                ),
                ("value_count", models.PositiveBigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_product_rollups",
                        to="websites.trackedsite",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["site", "event_name", "day"], name="daily_product_query_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("site", "day", "event_name"), name="daily_product_event_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalReportCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("site_selector", models.CharField(max_length=80)),
                ("report_type", models.CharField(max_length=32)),
                ("period", models.CharField(max_length=16)),
                ("parameters_hash", models.CharField(max_length=64)),
                ("parameters", models.JSONField(default=dict)),
                ("result", models.JSONField(default=dict)),
                ("archive_generation", models.CharField(max_length=64)),
                ("generated_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historical_report_cache",
                        to="websites.trackedsite",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["report_type", "period", "expires_at"],
                        name="historical_cache_query_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("site_selector", "report_type", "period", "parameters_hash"),
                        name="historical_report_cache_uniq",
                    )
                ],
            },
        ),
    ]
