# Generated by Django 5.2.16 on 2026-08-12 13:27

import hashlib
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone

import mcp_oauth.models


def backfill_refresh_families(apps, schema_editor):
    Family = apps.get_model("mcp_oauth", "OAuthRefreshFamily")
    RefreshToken = apps.get_model("mcp_oauth", "OAuthRefreshToken")
    AccessToken = apps.get_model("mcp_oauth", "OAuthAccessToken")
    database = schema_editor.connection.alias
    family_bindings = {}

    for token in RefreshToken.objects.using(database).order_by("created", "pk").iterator():
        resource = token.resource[0] if len(token.resource or []) == 1 else ""
        family_id = token.token_family or uuid.uuid4()
        binding = (token.user_id, token.application_id, resource)
        if family_id in family_bindings and family_bindings[family_id] != binding:
            # A corrupt UUID collision must not merge security principals.
            family_id = uuid.uuid4()
        if family_id not in family_bindings:
            family_bindings[family_id] = binding
            family = Family.objects.using(database).create(
                id=family_id,
                user_id=token.user_id,
                application_id=token.application_id,
                resource=resource,
                authorization_code_digest=token.authorization_code_digest,
                expires_at=token.family_expires_at,
            )
            Family.objects.using(database).filter(pk=family.pk).update(
                created_at=token.created,
                updated_at=token.updated,
            )
        token.family_state_id = family_id
        token.token_family = family_id
        token.save(update_fields=["family_state", "token_family"])

    migration_now = timezone.now()
    for family in Family.objects.using(database).all().iterator():
        members = RefreshToken.objects.using(database).filter(family_state_id=family.pk)
        first = members.order_by("created", "pk").first()
        if first is None:
            continue
        expiries = list(members.values_list("family_expires_at", flat=True))
        revocations = list(
            members.exclude(family_revoked_at=None).values_list(
                "family_revoked_at", flat=True
            )
        )
        code_digest = (
            members.exclude(authorization_code_digest="")
            .values_list("authorization_code_digest", flat=True)
            .first()
            or ""
        )
        revoked_at = min(revocations) if revocations else None
        if revoked_at is not None and revoked_at < first.created:
            revoked_at = first.created
        Family.objects.using(database).filter(pk=family.pk).update(
            created_at=first.created,
            expires_at=min(expiries),
            revoked_at=revoked_at,
            authorization_code_digest=code_digest,
        )
        members.update(
            family_expires_at=min(expiries),
            family_revoked_at=revoked_at,
        )
        if revoked_at is not None:
            access_ids = list(
                members.exclude(access_token_id=None).values_list(
                    "access_token_id", flat=True
                )
            )
            members.filter(revoked=None).update(revoked=migration_now)
            if access_ids:
                AccessToken.objects.using(database).filter(
                    pk__in=access_ids,
                    revoked_at=None,
                ).update(revoked_at=migration_now)

    # The prior (checksum, revoked) constraint admitted duplicate active NULL
    # rows. Preserve metadata, revoke every affected family, and assign a
    # non-credential synthetic checksum to all but one row before making the
    # checksum unconditionally unique.
    duplicates = (
        RefreshToken.objects.using(database)
        .values("token_checksum")
        .annotate(row_count=models.Count("pk"))
        .filter(row_count__gt=1)
    )
    for duplicate in duplicates.iterator():
        members = list(
            RefreshToken.objects.using(database)
            .filter(token_checksum=duplicate["token_checksum"])
            .order_by("pk")
        )
        family_ids = {member.family_state_id for member in members}
        Family.objects.using(database).filter(pk__in=family_ids).update(
            revoked_at=migration_now
        )
        family_members = RefreshToken.objects.using(database).filter(
            family_state_id__in=family_ids
        )
        access_ids = list(
            family_members.exclude(access_token_id=None).values_list(
                "access_token_id", flat=True
            )
        )
        family_members.update(
            revoked=migration_now,
            family_revoked_at=migration_now,
        )
        if access_ids:
            AccessToken.objects.using(database).filter(
                pk__in=access_ids,
                revoked_at=None,
            ).update(revoked_at=migration_now)
        for member in members[1:]:
            synthetic = hashlib.sha256(
                f"migrated-duplicate:{member.pk}:{duplicate['token_checksum']}".encode()
            ).hexdigest()
            RefreshToken.objects.using(database).filter(pk=member.pk).update(
                token_checksum=synthetic
            )


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_oauth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthRefreshFamily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource', models.TextField()),
                ('authorization_code_digest', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True, default=mcp_oauth.models.refresh_family_expiry)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='oauthrefreshtoken',
            name='mcp_oauth_refresh_sum_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='oauthrefreshtoken',
            name='mcp_oauth_refresh_family_ck',
        ),
        migrations.AddField(
            model_name='oauthrefreshfamily',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitehits_refresh_families', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ),
        migrations.AddField(
            model_name='oauthrefreshfamily',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_oauth_refresh_families', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oauthrefreshtoken',
            name='family_state',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='mcp_oauth.oauthrefreshfamily'),
        ),
    ]
